name: Electron Forge Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: electron
        
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npx electron-forge make
      
    - name: Debug file list
      run: ls -R out

    - name: List Subdirectories
      run: |
        find out -mindepth 1 -maxdepth 1 -type d > subdirs.txt
      shell: bash

    - name: Create and Upload Artifacts
      id: create-artifacts
      run: |
        while IFS= read -r dir; do
          zip -r "$dir.zip" "$dir"
          echo "::set-output name=artifacts::$dir.zip"
        done < subdirs.txt
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bubbifacts
        path: ${{ steps.create-artifacts.outputs.artifacts }}