name: Electron Forge Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: electron
        
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npx electron-forge make
      
    - name: Create and upload artifacts
      run: |
        for dir in out/*; do
          if [ -d "$dir" ]; then
            echo "Creating artifact for $dir"
            echo "::set-output name=artifact_path::$dir" >> $GITHUB_ENV
            echo "::set-output name=artifact_name::$(basename $dir)" >> $GITHUB_ENV
          fi
        done
      id: set-output

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.set-output.outputs.artifact_name }}
        path: ${{ steps.set-output.outputs.artifact_path }}

