name: Electron Forge Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: electron
        
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npx electron-forge make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: out

    - name: Publish Release
      id: publish
      uses: softprops/action-gh-release@v1
      with:
        files: out/**/*
        token: ${{ secrets.GITHUB_TOKEN }}
