name: Electron Forge Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: electron
        
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npx electron-forge make
      
    - name: Debug File Listing
      run: ls -R

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: out

